/* tslint:disable */
/* eslint-disable */
/**
 * ApeRAG API
 * ApeRAG API Documentation
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface Settings
 */
export interface Settings {
    /**
     * Whether to use MinerU
     * @type {boolean}
     * @memberof Settings
     */
    'use_mineru'?: boolean;
    /**
     * API token for MinerU
     * @type {string}
     * @memberof Settings
     */
    'mineru_api_token'?: string;
    /**
     * Whether to use DocRay
     * @type {boolean}
     * @memberof Settings
     */
    'use_doc_ray'?: boolean;
    /**
     * Whether to use MarkItDown
     * @type {boolean}
     * @memberof Settings
     */
    'use_markitdown'?: boolean;
    /**
     * Whether to enable DingTalk integration
     * @type {boolean}
     * @memberof Settings
     */
    'dingtalk_enabled'?: boolean;
    /**
     * DingTalk callback signature secret
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_webhook_secret'?: string;
    /**
     * DingTalk outgoing robot webhook URL
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_outgoing_webhook_url'?: string;
    /**
     * DingTalk outgoing robot webhook secret
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_outgoing_webhook_secret'?: string;
    /**
     * Bound SAPilot Agent Bot ID for DingTalk
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_bot_id'?: string;
    /**
     * DingTalk response mode: sync or webhook
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_response_mode'?: string;
    /**
     * DingTalk robot code for file downloads
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_robot_code'?: string;
    /**
     * DingTalk app key
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_app_key'?: string;
    /**
     * DingTalk app secret
     * @type {string}
     * @memberof Settings
     */
    'dingtalk_app_secret'?: string;
}
